/* PRO 4 interactions: performance-first rose garden, countdown, music ducking */
(function(){
'use strict';
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const mainAudio=$('#birthdayMusic'), letterAudio=$('#letterMusic'), env=$('#envelopeButton'), modal=$('#letterModal');
const tracks=['music/song.mp3','music/song-2.mp3','music/song-3.mp3','music/song-4.mp3'];
const key='suhaila-main-track-history-v4';
function chooseTrack(){let used=[];try{used=JSON.parse(localStorage.getItem(key)||'[]')}catch(e){};let available=tracks.filter(x=>!used.includes(x));if(!available.length){used=[];available=tracks.slice()};const pick=available[Math.floor(Math.random()*available.length)];used.push(pick);try{localStorage.setItem(key,JSON.stringify(used.slice(-tracks.length)))}catch(e){};return pick}
function setupMusic(){if(!mainAudio)return;mainAudio.src=chooseTrack();mainAudio.loop=true;mainAudio.volume=.72;letterAudio&&(letterAudio.volume=.62);document.addEventListener('visibilitychange',()=>{if(document.hidden&&letterAudio&&!letterAudio.paused)letterAudio.pause()});}
function duck(){if(!mainAudio||!letterAudio)return;const from=mainAudio.volume,t=performance.now();function f(n){let p=Math.min(1,(n-t)/1100);mainAudio.volume=from*(1-p)+.075*p;if(p<1)requestAnimationFrame(f)}requestAnimationFrame(f);letterAudio.currentTime=0;letterAudio.play().catch(()=>{});}
function unduck(){if(!mainAudio||!letterAudio)return;const from=mainAudio.volume,t=performance.now();letterAudio.volume=.62;function f(n){let p=Math.min(1,(n-t)/1000);mainAudio.volume=from*(1-p)+.72*p;if(p<1)requestAnimationFrame(f)}requestAnimationFrame(f);let a=letterAudio.volume;function g(n){let p=Math.min(1,(n-t)/850);letterAudio.volume=a*(1-p);if(p<1)requestAnimationFrame(g);else letterAudio.pause()}requestAnimationFrame(g)}
function hookEnvelope(){if(!env)return;env.addEventListener('click',()=>{setTimeout(duck,850)});if(modal){const close=$('#closeLetter',modal),backdrop=$('.backdrop',modal);[close,backdrop].forEach(x=>x&&x.addEventListener('click',()=>setTimeout(unduck,80)));document.addEventListener('keydown',e=>{if(e.key==='Escape')setTimeout(unduck,80)})}}
function countdown(){const ids=['cdDays','cdHours','cdMinutes','cdSeconds'].map(x=>$('#'+x)),label=$('#countdownLabel');if(ids.some(x=>!x))return;function tick(){const now=new Date(),year=now.getFullYear(), target=new Date(year,8,20,0,0,0);let next=target;if(now>=target)next=new Date(year+1,8,20,0,0,0);let ms=next-now;const days=Math.floor(ms/864e5);ms%=864e5;const h=Math.floor(ms/36e5);ms%=36e5;const m=Math.floor(ms/6e4);const s=Math.floor((ms%6e4)/1000);[days,h,m,s].forEach((v,i)=>ids[i].textContent=String(v).padStart(2,'0'));label.textContent=now>=target?`20 سبتمبر ${year+1} · عيد ميلاد سُهيلة القادم`:'20 سبتمبر 2026 · منتصف الليل';}tick();setInterval(tick,1000)}
function roses(){const sections=$$('.scene');sections.forEach((sec,si)=>{if(sec.classList.contains('hero')||sec.id==='starMap')return;let garden=document.createElement('div');garden.className='rose-garden';const count=si%2?2:3;for(let i=0;i<count;i++){const r=document.createElement('span');r.className='real-rose';r.style.setProperty('--size',(70+Math.random()*70)+'px');r.style.left=(Math.random()*92)+'%';r.style.top=(Math.random()*86)+'%';r.style.setProperty('--rot',(Math.random()*50-25)+'deg');r.innerHTML='<span class="center"></span><span class="rose-stem"></span><span class="rose-leaf" style="left:-28px;top:72px;transform:rotate(-25deg)"></span>';garden.appendChild(r)}sec.appendChild(garden)});}
function particleAtTwenty(){const section=$('#twenty');if(!section)return;const io=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;for(let i=0;i<18;i++){const p=document.createElement('i');p.className='twenty-particle';p.style.left=Math.random()*100+'%';p.style.animationDelay=Math.random()*2+'s';section.appendChild(p);setTimeout(()=>p.remove(),6000)}io.disconnect()}),{threshold:.35});io.observe(section)}
function init(){setupMusic();hookEnvelope();countdown();roses();particleAtTwenty();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
